Cut v1.1.2 release
atlassian-labs/cyclops pull request #23
Opened 2020-12-11 00:19 UTC by cespo

Branch build "e27f8f2" has been soaking on internal clusters for quite some time now.
Cutting a new release

2020-12-11 00:20 UTC, vincentportella approved these changes

2020-12-11 00:42 UTC, awprice requested changes
This should be a 1.2.0 release, given that we have added a new feature and not fixed any bugs.

2020-12-11 03:56 UTC, awprice approved these changes
Thanks!

2020-12-13 23:03 UTC, vincentportella approved these changes

2020-12-13 23:43 UTC, merged