Force delete pods off the node if they have been unhealthy for a while when cycling
atlassian-labs/cyclops pull request #35
Opened 2021-06-10 06:47 UTC by mwhittington21

Fixes #34

2021-06-10 06:58 UTC, awprice requested changes
Logic looks good, really just some minor changes

2021-06-10 06:58 UTC, awprice commented on Makefile
> +VERSION = 1.6.0
We should bump the version and release independently after testing internally.

2021-06-10 06:59 UTC, awprice commented on pkg/k8s/pod.go
> +func KillAndRemovePod(podName, podNamespace, nodeName string, client kubernetes.Interface) error {
I think this should be `ForciblyDeletePod` - it better describes what we are actually performing on the pod.

Log lines below should be updated to match

2021-06-10 07:13 UTC, awprice commented on pkg/k8s/pod.go
> +func EvictOrKillPod(pod *v1.Pod, apiVersion string, client kubernetes.Interface, unhealthyAfter time.Duration, now time.Time) error {
nit: should be EvictOrForciblyDeletePod

2021-06-10 07:24 UTC, awprice approved these changes
LGTM

2021-06-11 01:28 UTC, dtnyn approved these changes

2021-06-11 03:36 UTC, Jacobious52 approved these changes

2021-06-11 03:36 UTC, merged